version: "3.9"
services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/root_caddy:/root/.local/caddy
      - ./caddy/data:/data # Optional
      - ./caddy/config:/config # Optional

    environment:
      - JWT_SHARED_KEY=${JWT_SHARED_KEY}
      - DOMAIN=${DOMAIN}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - GITHUB_CLIENT_ID=${GIT_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GIT_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - dev
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          sls_key: ${SERVERLESS_KEY}
          name: ${GIT_NAME}
          email: ${GIT_EMAIL}
    container_name: dev
    hostname: dev
    #platform: "linux/x86_64"
    #platform: "linux/amd64"
    volumes:
      - "venv:/home/workspace/venv"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "src:/home/workspace/src"
    ports:
      - "${VSCODE_PORT}:3000"
    restart: always
volumes:
  venv:
    name: venv_volume_${CONTAINER_NAME}
  src:
    name: dev_volume_${CONTAINER_NAME}